#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
   
write_files:
  - path: /home/azureuser/ora-vm-script-params.sh
    owner: azureuser:azureuser
    permissions: '0755'
    content: |
      oraMntDir=${oraMntDir}
      ANFipAddr=${ANFipAddr}
      ANFvolumeName=${ANFvolumeName}
